package com.serviceos.shared;

/**
 * 首条纵向切片使用的稳定错误码。HTTP 文案允许演进，客户端只能依赖这里的错误码语义。
 */
public enum ProblemCode {
    UNAUTHENTICATED,
    ACCESS_DENIED,
    VALIDATION_FAILED,
    IDEMPOTENCY_KEY_REUSED,
    IDEMPOTENCY_IN_PROGRESS,
    EVENT_PAYLOAD_MISMATCH,
    INBOX_IN_PROGRESS,
    OUTBOX_LEASE_LOST,
    TASK_SCHEDULE_CONFLICT,
    TASK_LEASE_LOST,
    TASK_STATE_CONFLICT,
    VERSION_CONFLICT,
    FILE_UPLOAD_CONFLICT,
    FILE_UPLOAD_EXPIRED,
    FILE_FINALIZE_IN_PROGRESS,
    FILE_OBJECT_MISMATCH,
    FILE_NOT_AVAILABLE,
    PROJECT_CODE_ALREADY_EXISTS,
    RESOURCE_NOT_FOUND,
    INTERNAL_ERROR
}
