package com.serviceos.shared;

/**
 * 首条纵向切片使用的稳定错误码。HTTP 文案允许演进，客户端只能依赖这里的错误码语义。
 */
public enum ProblemCode {
    UNAUTHENTICATED,
    ACCESS_DENIED,
    VALIDATION_FAILED,
    IDEMPOTENCY_KEY_REUSED,
    IDEMPOTENCY_IN_PROGRESS,
    EVENT_PAYLOAD_MISMATCH,
    INBOX_IN_PROGRESS,
    OUTBOX_LEASE_LOST,
    TASK_SCHEDULE_CONFLICT,
    TASK_LEASE_LOST,
    TASK_STATE_CONFLICT,
    TASK_ASSIGNMENT_CONFLICT,
    TASK_EXECUTION_GUARDED,
    DISPATCH_CAPACITY_CONFLICT,
    SERVICE_ASSIGNMENT_CONFLICT,
    APPOINTMENT_VERSION_CONFLICT,
    APPOINTMENT_WINDOW_NOT_ENDED,
    TECHNICIAN_ASSIGNMENT_CHANGED,
    VISIT_VERSION_CONFLICT,
    VISIT_GEOFENCE_REJECTED,
    FORM_VERSION_CONFLICT,
    FORM_SUBMISSION_NOT_VALIDATED,
    FORM_RUNTIME_UNSUPPORTED,
    VERSION_CONFLICT,
    FILE_UPLOAD_CONFLICT,
    FILE_UPLOAD_EXPIRED,
    FILE_FINALIZE_IN_PROGRESS,
    FILE_OBJECT_MISMATCH,
    FILE_NOT_AVAILABLE,
    PROJECT_CODE_ALREADY_EXISTS,
    RESOURCE_NOT_FOUND,
    INTERNAL_ERROR
}
