import zhCN from 'ant-design-vue/es/locale/zh_CN'

export {
  Avatar,
  Badge,
  Button,
  Card,
  Checkbox,
  ConfigProvider,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Flex,
  Form,
  Input,
  Menu,
  message,
  Modal,
  Pagination,
  Radio,
  Result,
  Row,
  Col,
  Select,
  Skeleton,
  Space,
  Statistic,
  Steps,
  Table,
  Tabs,
  Tag,
  Tooltip,
} from 'ant-design-vue'
export type { TableColumnsType } from 'ant-design-vue'
export {
  AppstoreOutlined,
  AuditOutlined,
  BellOutlined,
  CalendarOutlined,
  CheckOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CopyOutlined,
  DownOutlined,
  DownloadOutlined,
  FileDoneOutlined,
  HomeOutlined,
  MenuFoldOutlined,
  QuestionCircleOutlined,
  RightOutlined,
  SafetyCertificateFilled,
  SearchOutlined,
  SettingOutlined,
  TeamOutlined,
  ToolOutlined,
  UserAddOutlined,
  WarningOutlined,
} from '@ant-design/icons-vue'

export const serviceOsZhCN = zhCN
